
replicaCount: 3

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts: 
    - business-account-api.app.pr.adform.zone
  tls:
    - hosts: [business-account-api.app.pr.adform.zone]

resources:
 limits:
   cpu: 1000m
   memory: 3Gi
 requests:
   cpu: 300m
   memory: 1.5Gi
    
autoscaler:
  enabled: true
  maxReplicaCount: 5
  targetAverageUtilization: 90

environment:
  ASPNETCORE_ENVIRONMENT: pr
